name: klin
description: Klin language compiler targeting C.
version: 0.1.4
repository: https://github.com/klin-lang/klin

environment:
  sdk: ^3.5.0

executables:
  klin: klin

dev_dependencies:
  test: ^1.25.0
dependencies:
  crypto: ^3.0.7
  json_rpc_2: ^4.0.0
  lsp_server: ^0.4.0
  xml: ^7.0.1
