import 'parse.dart';

/// Emit Klin enums for an [IocPinout] (issue 074).
///
/// `BoardPort.<name>` = port index (A=0…); `BoardPin.<name>` = pin number.
String emitIocPinout(IocPinout pinout, {String? sourceNote}) {
  final buf = StringBuffer();
  buf.writeln('// generated by \$board — pinout only (issue 074); not HAL');
  if (sourceNote != null && sourceNote.isNotEmpty) {
    buf.writeln('// source: $sourceNote');
  }
  if (pinout.pins.isEmpty) {
    buf.writeln('// (no labeled GPIO pins found in .ioc)');
    return buf.toString();
  }

  buf.writeln('enum BoardPort: i32 {');
  for (final p in pinout.pins) {
    buf.writeln('  // ${p.name} → P${p.port}${p.pin}');
    buf.writeln('  ${p.name} = ${p.portIndex}');
  }
  buf.writeln('}');
  buf.writeln('enum BoardPin: i32 {');
  for (final p in pinout.pins) {
    buf.writeln('  // ${p.name} → P${p.port}${p.pin}');
    buf.writeln('  ${p.name} = ${p.pin}');
  }
  buf.writeln('}');
  return buf.toString();
}
